@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US470

autonumber

actor "Utente"

"Utente" -> "<<C4:System>>\n:RobDroneGo": Solicita lista de requisições
activate "<<C4:System>>\n:RobDroneGo"
"<<C4:System>>\n:RobDroneGo" --> "Utente": Mostra lista de requisições disponiveis
deactivate "<<C4:System>>\n:RobDroneGo"

"Utente" -> "<<C4:System>>\n:RobDroneGo": Aprova/Recusa requisição
activate "<<C4:System>>\n:RobDroneGo"
"Utente" <-- "<<C4:System>>\n:RobDroneGo": Mensagem de sucesso da operação
deactivate "<<C4:System>>\n:RobDroneGo"

@enduml