@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Container Sequence Diagram (SSD) - US150 (N2)

autonumber

actor "Gestor de Campus"

activate "Gestor de Campus"
"Gestor de Campus" -> "<<C4:Container>>\n:Visualização": Inicia operação de criar edifício
activate "<<C4:Container>>\n:Visualização"
"<<C4:Container>>\n:Visualização" --> "Gestor de Campus": Solicita dados necessários (buildingId, buildingName,\nbuildingDescription, numberOfFloors, dimX, dimY)
deactivate "<<C4:Container>>\n:Visualização"

"Gestor de Campus" -> "<<C4:Container>>\n:Visualização": Introduz dados solicitados
activate "<<C4:Container>>\n:Visualização"
"<<C4:Container>>\n:Visualização" --> "<<C4:Container>>\nMódulo de Gestão\nde Informação": POST /buildings/ {buildingId, buildingName,\nbuildingDescription, numberOfFloors, dimX, dimY)}
activate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\nMódulo de Gestão\nde Informação" --> "<<C4:Container>>\n:Visualização": 200 OK building
deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"Gestor de Campus" <-- "<<C4:Container>>\n:Visualização": Mostra edifício que acaba de ser criado e seus parametros
deactivate "<<C4:Container>>\n:Visualização"
deactivate "Gestor de Campus"

@enduml