@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Container Sequence Diagram (SSD) - US240 (N2)

autonumber

actor "Gestor de Campus"

"Gestor de Campus" -> "<<C4:Container>>\n:Visualização": Inicia operação de criação de edifício
activate "<<C4:Container>>\n:Visualização"
"<<C4:Container>>\n:Visualização" --> "Gestor de Campus": Solicita dados necessários (BuildingId, BuildingName, \nBuildingDescription, buildingNumberOfFloors, dimX, dimY)
deactivate "<<C4:Container>>\n:Visualização"

"Gestor de Campus" -> "<<C4:Container>>\n:Visualização": Introduz dados solicitados
activate "<<C4:Container>>\n:Visualização"
"<<C4:Container>>\n:Visualização" --> "<<C4:Container>>\nMódulo de Gestão\nde Informação": POST /buildings/ {BuildingId, BuildingName, \nBuildingDescription, buildingNumberOfFloors, dimX, dimY, \n floors, elevators}
activate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\nMódulo de Gestão\nde Informação" --> "<<C4:Container>>\n:Visualização": 200 OK connection
deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"Gestor de Campus" <-- "<<C4:Container>>\n:Visualização": Mostra o edifício criado
deactivate "<<C4:Container>>\n:Visualização"

@enduml