@startuml
left to right direction

actor "Utente"
actor "Administrador"
actor "Utilizador"
actor "Gestor de Tarefas"

(Utente) --> (Registar-me como utente do sistema)
(Utente) --> (Retificar/Alterar os meus dados)
(Utente) --> (Uma cópia dos meus dados pessoais)
(Utente) --> (Cancelar a minha conta garantindo que os meus\ndados são apagados)
(Utente) --> (Requisitar uma tarefa indicando os parâmetros\nnecessários à sua execução, nomeadamente\no ponto inicial e\no término e qual a tarefa pretendida)

(Administrador) --> (Aprovar ou recusar o registo de um utente)
(Administrador) --> (Criar um utilizador de sistema indicando\nas suas permissões)

(Utilizador) --> (Menu da aplicação se ajuste ao meu tipo de utilizador)

(Gestor de Tarefas) --> (Aprovar/Reprovar requisição de uma tarefa)
(Gestor de Tarefas) --> (Consultar as requisições de tarefas ainda não aprovadas)
(Gestor de Tarefas) --> (Pesquisar as requisições de tarefas por estado,\npor tipo de dispositivo, ou utente)
(Gestor de Tarefas) --> (Obter a sequencia de execução das tarefas aprovadas)






@enduml

