@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US1130 (N2)

autonumber

actor "Gestor de Campus"

"Gestor de Campus" -> "<<C4:Container>>\n:Visualização": Solicita criação de elevador
activate "<<C4:Container>>\n:Visualização"
"<<C4:Container>>\n:Visualização" -> "<<C4:Container>>\nMódulo de Gestão\nde Informação": GET /buildings/
activate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\nMódulo de Gestão\nde Informação" --> "<<C4:Container>>\n:Visualização": 200 OK buildings
deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\n:Visualização" -> "<<C4:Container>>\nMódulo de Gestão\nde Informação": GET /floors/
activate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\nMódulo de Gestão\nde Informação" --> "<<C4:Container>>\n:Visualização": 200 OK floors
deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\n:Visualização" -> "<<C4:Container>>\nMódulo de Gestão\nde Informação": GET /elevators/
activate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\nMódulo de Gestão\nde Informação" --> "<<C4:Container>>\n:Visualização": 200 OK elevators
deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\n:Visualização" --> "Gestor de Campus": Solicita dados necessários
deactivate "<<C4:Container>>\n:Visualização"

"Gestor de Campus" -> "<<C4:Container>>\n:Visualização": Introduz dados solicitados
activate "<<C4:Container>>\n:Visualização"
"<<C4:Container>>\n:Visualização" -> "<<C4:Container>>\nMódulo de Gestão\nde Informação": POST /elevators/
activate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\nMódulo de Gestão\nde Informação" --> "<<C4:Container>>\n:Visualização": 201 OK elevator
deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"Gestor de Campus" <-- "<<C4:Container>>\n:Visualização": Mensagem de sucesso
deactivate "<<C4:Container>>\n:Visualização"

@enduml