@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US1060

autonumber

actor "Gestor de Campus"

activate "Gestor de Campus"
"Gestor de Campus" -> "<<C4:System>>\n:RobDroneGo": Solicita a listagem de todos os edifícios
activate "<<C4:System>>\n:RobDroneGo"
activate "<<C4:System>>\n:RobDroneGo"
"Gestor de Campus" <-- "<<C4:System>>\n:RobDroneGo": Lista de edifícios com os seus\nrespetivos parâmetros
deactivate "<<C4:System>>\n:RobDroneGo"
@enduml