@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US160

autonumber

actor "Gestor de Campus"

activate "Gestor de Campus"
"Gestor de Campus" -> "<<C4:System>>\n:RobDroneGo": Solicita edição de edifício
activate "<<C4:System>>\n:RobDroneGo"
"<<C4:System>>\n:RobDroneGo" --> "Gestor de Campus": Solicita dados necessários (buildingId, buildingName,\nbuildingDescription, numberOfFloors, dimX, dimY)
deactivate "<<C4:System>>\n:RobDroneGo"

"Gestor de Campus" -> "<<C4:System>>\n:RobDroneGo": Introduz dados solicitados
activate "<<C4:System>>\n:RobDroneGo"
"Gestor de Campus" <-- "<<C4:System>>\n:RobDroneGo": Mensagem de sucesso da operação
deactivate "<<C4:System>>\n:RobDroneGo"
@enduml