name: deployment schedule

on:
  schedule:
    - cron: '25 6 * * *'
  workflow_dispatch:
    # This allows manual triggering
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13
          
      - name: Install dependencies
        run: npm install
        working-directory: frontend/angular-app

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Run tests
        run: ng test
        working-directory: frontend/angular-app

      - name: Deploy and build
        if: success()
        run: |
          ng build --configuration=production
          sshpass -p 'eheRVge/wN5hSsZd4D9Y' scp -r dist root@10.9.22.76:/var/www/frontend
        working-directory: frontend/angular-app
