@startuml

skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing true

actor GestorDeFrota as GestorDeFrota
activate GestorDeFrota
GestorDeFrota -> Frontend: inibRobot
activate Frontend
Frontend --> GestorDeFrota: data request
deactivate Frontend
GestorDeFrota -> Frontend: data response
activate Frontend
Frontend -> ModuloDeGestaoDeInformaçao: patch(robot)
activate ModuloDeGestaoDeInformaçao
ModuloDeGestaoDeInformaçao --> Frontend: 201 (Success)
deactivate ModuloDeGestaoDeInformaçao
Frontend -> GestorDeFrota: success
deactivate Frontend

@enduml