@startuml
skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing true

actor GestorDeFrota as GestorDeFrota

activate GestorDeFrota
GestorDeFrota -> View: inibRobot
activate View
View -> Component: ngInit()
activate Component
Component -> Service: getr()
activate Service
Service -> MódulodeGestãodeInformação : getRobot()
activate MódulodeGestãodeInformação
MódulodeGestãodeInformação -> MódulodeGestãodeInformação: middleware.rolecheck\n("Admin" || "Gestor de Frota")
MódulodeGestãodeInformação --> Service : Lista de robot
deactivate MódulodeGestãodeInformação
Service --> Component : Lista de robot
deactivate Service
Component --> View : robot
deactivate Component
View -> GestorDeFrota: robot
deactivate View

GestorDeFrota -> View: inibRobot
activate View
View --> GestorDeFrota: data request
deactivate View
GestorDeFrota -> View: data required
activate View
View -> Component: inibRobot(data)
activate Component
Component -> Service: inibRobot(data)
activate Service
Service -> MódulodeGestãodeInformação: patch(robot)
activate MódulodeGestãodeInformação
MódulodeGestãodeInformação -> MódulodeGestãodeInformação: middleware.rolecheck\n("Admin" || "Gestor de Frota")
MódulodeGestãodeInformação -> Service: 201(robot)
deactivate MódulodeGestãodeInformação
Service -> Component: 201(robot)
deactivate Service
Component -> View: 201(robot)
deactivate Component
View -> GestorDeFrota: success

@enduml