@startuml

skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing true

actor GestorDeFrota as GestorDeFrota

activate GestorDeFrota
GestorDeFrota -> RobDroneGo: inibRobot
activate RobDroneGo
RobDroneGo --> GestorDeFrota: data request
GestorDeFrota -> RobDroneGo : data response
RobDroneGo -> GestorDeFrota: success
deactivate RobDroneGo

@enduml