@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Container Sequence Diagram (SD) - US1180 (N3)

autonumber

actor "Gestor de Campus"

"Gestor de Campus" -> "<<C4:Container>>\n:Visualização": Inicia operação de editar passagem entre\ndois edifícios
activate "<<C4:Container>>\n:Visualização"
"<<C4:Container>>\n:Visualização" -> Component: ngInit()
activate Component
Component -> Service: getBuildings()
activate Service
Service -> "<<C4:Container>>\nMódulo de Gestão\nde Informação" : getBuildings()
activate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\nMódulo de Gestão\nde Informação" -> "<<C4:Container>>\nMódulo de Gestão\nde Informação": middleware.rolecheck\n("Admin" || "Gestor de Campus")
"<<C4:Container>>\nMódulo de Gestão\nde Informação" --> Service : Lista de edifícios
deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
Service --> Component : Lista de edifícios
deactivate Service
Component -> Service : getFloors()
activate Service
Service -> "<<C4:Container>>\nMódulo de Gestão\nde Informação" : getFloors()
activate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\nMódulo de Gestão\nde Informação" -> "<<C4:Container>>\nMódulo de Gestão\nde Informação": middleware.rolecheck\n("Admin" || "Gestor de Campus")
"<<C4:Container>>\nMódulo de Gestão\nde Informação" --> Service : Lista de pisos
deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
Service --> Component : Lista de pisos
deactivate Service
Component -> Service : getConnections()
activate Service

Service -> "<<C4:Container>>\nMódulo de Gestão\nde Informação" : getConnections()
activate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\nMódulo de Gestão\nde Informação" -> "<<C4:Container>>\nMódulo de Gestão\nde Informação": middleware.rolecheck\n("Admin" || "Gestor de Campus")
"<<C4:Container>>\nMódulo de Gestão\nde Informação" --> Service: Lista de passagens
deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
Service --> Component: Lista de passagens
deactivate Service
Component --> "<<C4:Container>>\n:Visualização" : buildings, floors, connections
deactivate Component

"<<C4:Container>>\n:Visualização" --> "Gestor de Campus": Solicita dados que pretende mudar
deactivate "<<C4:Container>>\n:Visualização"

"Gestor de Campus" -> "<<C4:Container>>\n:Visualização": Introduz dados solicitados
activate "<<C4:Container>>\n:Visualização"
"<<C4:Container>>\n:Visualização" -> Component : update(connection)
activate Component
Component -> Service : update(connection)
activate Service
Service -> "<<C4:Container>>\nMódulo de Gestão\nde Informação" : update(connection)

activate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"<<C4:Container>>\nMódulo de Gestão\nde Informação" -> "<<C4:Container>>\nMódulo de Gestão\nde Informação": middleware.rolecheck\n("Admin" || "Gestor de Campus")
"<<C4:Container>>\nMódulo de Gestão\nde Informação" --> Service: 201 OK connection
note right: Módulo de Gestão de Informação\né a representação do Sprint A

deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
Service --> Component: 201 OK connection
deactivate Service
Component --> "<<C4:Container>>\n:Visualização" : 201 OK connection
deactivate Component
deactivate "<<C4:Container>>\nMódulo de Gestão\nde Informação"
"Gestor de Campus" <-- "<<C4:Container>>\n:Visualização": Mensagem de sucesso
deactivate "<<C4:Container>>\n:Visualização"

@enduml