@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US1180

autonumber

actor "Gestor de Campus"

"Gestor de Campus" -> "<<C4:System>>\n:RobDroneGo": Solicita edição de passagem entre edifícios
activate "<<C4:System>>\n:RobDroneGo"
"<<C4:System>>\n:RobDroneGo" --> "Gestor de Campus": Solicita dados necessários (connectionId,\nbuildingfromId, buildingtoId, floorfromId, floortoId,\n locationX, locationY)
deactivate "<<C4:System>>\n:RobDroneGo"

"Gestor de Campus" -> "<<C4:System>>\n:RobDroneGo": Introduz dados solicitados
activate "<<C4:System>>\n:RobDroneGo"
"Gestor de Campus" <-- "<<C4:System>>\n:RobDroneGo": Mensagem de sucesso da operação
deactivate "<<C4:System>>\n:RobDroneGo"

@enduml